dist: trusty
sudo: false

language: node_js

if: tag = blank

git:
  depth: 1

install: cd docs && npm install

script: node version-transcompiler.js

before_deploy:
 - cd ../Build/
 - zip -o -9 -r -q "Cemu1.14.0GFXPacks-V$TRAVIS_BUILD_NUMBER"".zip" ./*

deploy:
  provider: releases
  api_key:
    secure: xTDSKtTaEaNDYdJjylSQZqp13Drrywu96V+XrL3gL51iE7ptHatvJCYxUniMWVHU6XmWDuqwMn1gQzUOIQcm9l9otjil9lhtyp1J8NxfYa5RxZifA70hlFHcNH+N061rzbeI2IhSw9bqFJXT/772P/ZgKvVm8fl+XhTQ/iSiMGF1hjeMzJtCqkCiThTlBB+5/IGU9rTHZ6ns/w8g/YujarOBVxC7oybqa0p2I3UNUhl0jIo5HIhJ4EUubU2wv0SWOvpv2hutj5Os6VwdfvX/T0F/EzS/KXeFVe+iDAqkzuj36ck8sPuyZ7bIdibUnTzF/YsSJtajSXtFfcwTn8gJffNxQhC9AU2gIvzbomMTj9LSNp56Zii/gC45O5v+Un8iQ2RQZzUlwT6ORDv5nvdgP1UXdZCvrNTMwS4znGcl88b5b8UDioOxtLLhs+dSueeDOravF0WVIa1p4r6ZTcx1Rdae84qRlmxV2lJrpzPMUkczPQlashyHlEWoYEHGlznzt6fL/wOB5JoCY89HFfGW/ARYJi7ccfO54sLxZPFJfBoWg508dudkwTpLQKlTD8h4bSTcNmPb4ZHS9khFaOru9VRXKl6KmuLlpjH9eZbExBN0LUbKWuDZCpoxjO6wufw4+MMpAmzHyzw8ixK0uE+0FkW388dkzm/NAsL4ZJ/1cbc=
  file: "Cemu1.14.0GFXPacks-V$TRAVIS_BUILD_NUMBER"".zip"
  skip_cleanup: true
  on:
    tags: false
