dist: trusty
sudo: false
language: node_js
node_js:
  - "node"

git:
  depth: 1

install: cd docs && npm install

script: node version-transcompiler.js

before_deploy:
 - cd ../Build/
 - zip -o -9 -r -q "Cemu1.14.0GFXPacks-$TRAVIS_BUILD_NUMBER"".zip" ./*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  name: 'Cemu 1.14.0 Graphic Pack Releases'
  file_glob: true
  file: ./*.zip
  on:
    tags: false
    repo: slashiee/gfx_pack
