dist: trusty
sudo: false
language: node_js

if: tag IS blank

git:
  depth: 1


install: cd docs && npm install

script: node version-transcompiler.js

before_deploy:
 - cd ../Build/
 - zip -o -9 -r -q "Cemu1.14.0GFXPacks-V$TRAVIS_BUILD_NUMBER"".zip" ./*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YTcExSFAx7QMMFiRU6JRsLupa6eis/q4fq2L4DMguixp40sC73+ROIQEknSa79CDmv0uXsFuAVuOnnVNIIqJQQCQ8Hg4Sutbuozsi2P0/DjlQzIDswpNvh2XjxqKOR+q/HGykA4i+jyaPa+t4eInKRtWtPW3eacc0ALOXMquc8Oc1ImDtmrhWgvBtRIQZDC/1bG5J56UbfGhyK31m3NlMLhAnhC9nshY$  file: Cemu1.14.0GFXPacks
  file: "Cemu1.14.0GFXPacks-$TRAVIS_BUILD_NUMBER"".zip"
  on:
    tags: false
    repo: slashiee/gfx_pack