dist: trusty
sudo: false
language: node_js
node_js:
  - "node"

git:
  depth: 1

env:
  global:
    secure: JkXrZEYH1PvXUpI02PYZC9csCtHDS9C41vMMWZZ4gIlkugFQGwVqB2aOjCbiCZzo5PiBXqz9p+xcRHk97SnzCLBINovw3GgWw1YUApYNXDARAOvZVrWMUQhqiouezexPUfL0dxJW5T1it6zN+weAiDsdfgJB8Q++TOQbn2mbcVfRNoR/HCO0v/5P0rtmtqPLbvtLj76eesVVr5rmC8SRDv7x/kCj4fHFYlS7tQGE6nV8XHo0FLr9cPafuqPjsIXR/QnJR+XYMsQfi8LymBEfv92Fq47J+nS9+iGG3M+T+n3GQ8lAjx6gGeiNnfVXQB8rMNItBuFsNfu+iiyurw4uMFaP66+GgamosyuPM+Tw7p4zc/WP316enAYZ/aAbQsbV3BBZXfBy94iU/xNAq4T82QTNq2I3zS84MJnjQtNPBxmADEJ/EZN6SE+rDRq4KxsTCis+hWqiioaeF6rhF8z7Mbg3P6Hn/FesqyBSlRAHmq+bOJx5m2m7lww1DRTPeOH6vKut3yU6uSd+9let4K14AGgV4S0VdKRoTmZHLFUK+L6HkjERKDpeAWq1j4sKpBLPRXxKRmVFb9B9LJVGzAZQ4ad0gNLHP9SKHBF9DxwKESRNzY37FkRSj/rO8tASm4BZRiTVS/WUhTPig7C92+VuVedfTe7UHAX+2wow61qJlHQ=

if: tag IS blank

install: npm install -g github-release-cli@0.4.1

script:
  - cd Enhancements && zip -r -q -9 "../graphicPacks$TRAVIS_BUILD_NUMBER"".zip" ./* && cd ..
  - cd Source && zip -r -q -9 "../graphicPacks$TRAVIS_BUILD_NUMBER"".zip" ./* && cd ..
  - cd Modifications && zip -r -q -9 "../graphicPacks$TRAVIS_BUILD_NUMBER"".zip" ./* && cd ..
  - cd Workarounds && zip -r -q -9 "../graphicPacks$TRAVIS_BUILD_NUMBER"".zip" ./* && cd ..
  - |
    github-release upload \
      --owner=slashiee \
      --repo=gfx_pack \
      --tag="Travis$TRAVIS_BUILD_NUMBER" \
      --name="Graphic Packs: version $TRAVIS_BUILD_NUMBER" \
      --body="$(git log -1 --format='Commited at %ci by **%cn** in commit %h%n### %s%n```%n%b%n```%n')" \
      "graphicPacks$TRAVIS_BUILD_NUMBER"".zip"
